// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDiskAnalysis():Promise<Array<main.DiskEntry>>;

export function IsMoInstalled():Promise<boolean>;

export function RunAll(arg1:boolean):Promise<main.CommandResult>;

export function RunClean(arg1:boolean):Promise<main.CommandResult>;

export function RunInstall(arg1:boolean):Promise<main.CommandResult>;

export function RunOptimize(arg1:boolean):Promise<main.CommandResult>;

export function RunPurge(arg1:boolean):Promise<main.CommandResult>;
