// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDiskAnalysis() {
  return window['go']['main']['CommandService']['GetDiskAnalysis']();
}

export function IsMoInstalled() {
  return window['go']['main']['CommandService']['IsMoInstalled']();
}

export function RunAll(arg1) {
  return window['go']['main']['CommandService']['RunAll'](arg1);
}

export function RunClean(arg1) {
  return window['go']['main']['CommandService']['RunClean'](arg1);
}

export function RunInstall(arg1) {
  return window['go']['main']['CommandService']['RunInstall'](arg1);
}

export function RunOptimize(arg1) {
  return window['go']['main']['CommandService']['RunOptimize'](arg1);
}

export function RunPurge(arg1) {
  return window['go']['main']['CommandService']['RunPurge'](arg1);
}
