// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanDevCaches(arg1) {
  return window['go']['main']['DevCacheService']['CleanDevCaches'](arg1);
}

export function GetDevCaches() {
  return window['go']['main']['DevCacheService']['GetDevCaches']();
}
