// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanAICaches(arg1) {
  return window['go']['main']['DevCacheService']['CleanAICaches'](arg1);
}

export function CleanAppCaches(arg1) {
  return window['go']['main']['DevCacheService']['CleanAppCaches'](arg1);
}

export function CleanBrowserCaches(arg1) {
  return window['go']['main']['DevCacheService']['CleanBrowserCaches'](arg1);
}

export function CleanDevCaches(arg1) {
  return window['go']['main']['DevCacheService']['CleanDevCaches'](arg1);
}

export function GetAICaches() {
  return window['go']['main']['DevCacheService']['GetAICaches']();
}

export function GetAppCaches() {
  return window['go']['main']['DevCacheService']['GetAppCaches']();
}

export function GetBrowserCaches() {
  return window['go']['main']['DevCacheService']['GetBrowserCaches']();
}

export function GetDevCaches() {
  return window['go']['main']['DevCacheService']['GetDevCaches']();
}
