// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CleanDevCaches(arg1:Array<string>):Promise<Array<main.DevCacheResult>>;

export function GetDevCaches():Promise<Array<main.DevCacheTool>>;
