// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CleanAICaches(arg1:Array<string>):Promise<Array<main.DevCacheResult>>;

export function CleanAppCaches(arg1:Array<string>):Promise<Array<main.DevCacheResult>>;

export function CleanBrowserCaches(arg1:Array<string>):Promise<Array<main.DevCacheResult>>;

export function CleanDevCaches(arg1:Array<string>):Promise<Array<main.DevCacheResult>>;

export function GetAICaches():Promise<Array<main.CacheTarget>>;

export function GetAppCaches():Promise<Array<main.CacheTarget>>;

export function GetBrowserCaches():Promise<Array<main.CacheTarget>>;

export function GetDevCaches():Promise<Array<main.DevCacheTool>>;
