// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearHistory():Promise<boolean>;

export function GetHistory(arg1:number):Promise<Array<main.HistoryEntry>>;

export function Record(arg1:string,arg2:boolean,arg3:string,arg4:number):Promise<void>;
