// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['HistoryService']['ClearHistory']();
}

export function GetHistory(arg1) {
  return window['go']['main']['HistoryService']['GetHistory'](arg1);
}

export function Record(arg1, arg2, arg3, arg4) {
  return window['go']['main']['HistoryService']['Record'](arg1, arg2, arg3, arg4);
}
