// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FormatUptime(arg1:number):Promise<string>;

export function GetMetrics():Promise<main.SystemMetrics>;

export function GetWatchedProcesses():Promise<Array<main.WatchedProcess>>;
