// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function KillProcesses(arg1:Array<number>):Promise<Array<main.KillProcessResult>>;

export function ListFlaggedProcesses():Promise<Array<main.ProcessDetail>>;
