// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function KillProcesses(arg1) {
  return window['go']['main']['ProcessService']['KillProcesses'](arg1);
}

export function ListFlaggedProcesses() {
  return window['go']['main']['ProcessService']['ListFlaggedProcesses']();
}
