// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['SettingsService']['CheckForUpdate']();
}

export function IsLoginItem() {
  return window['go']['main']['SettingsService']['IsLoginItem']();
}

export function OpenPrivacySettings() {
  return window['go']['main']['SettingsService']['OpenPrivacySettings']();
}

export function SetLoginItem(arg1) {
  return window['go']['main']['SettingsService']['SetLoginItem'](arg1);
}
