// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function IsLoginItem():Promise<boolean>;

export function SetLoginItem(arg1:boolean):Promise<boolean>;
